Insight metrics implementation
mercadopago/sdk-php pull request #248
Opened 2020-03-17 14:06 UTC by phgoncalves

- Added insight metrics implementation
To test this changes locally you can install the dependency with the following command:
`composer require "mercadopago/dx-php:dev-release/1.9.0"`

2020-03-18 17:28 UTC, rafgod-ML reviewed
Chicos les deje unas consultas, en principio eso,  voy a probar el codigo y debuguear a ver si los puedo ayudar con los campos que faltan

2020-03-18 17:28 UTC, rafgod-ML commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
falta nameserver-address este campos se podrian obtener con CURL?

2020-03-18 17:28 UTC, rafgod-ML commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
falta Retry

2020-03-18 17:28 UTC, rafgod-ML commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
falta user-agent, network-type, was-reused, certificate-info, tcp-info estos campos se podrian obtener con CURL?

2020-03-20 17:25 UTC, phgoncalves commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
@rafgod-ML Curl no expone el retry count.

2020-03-20 17:26 UTC, phgoncalves commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
Agregado!

2020-03-20 17:26 UTC, phgoncalves commented on src/MercadoPago/Entities/Insight/InsightDataManager.php
> +
Agregue la info que se tiene disponible

2020-03-25 20:07 UTC, rafgod-ML requested changes

2023-09-04 19:12 UTC, closed without merging