added build version
mercadopago/sdk-php pull request #366
Opened 2022-07-14 16:17 UTC by lucmkz

added build_version attribute

2022-07-14 17:18 UTC, lucmantovani approved these changes

2022-07-14 18:45 UTC, gdeandradero approved these changes

2022-07-14 22:02 UTC, eltinMeli requested changes
Faltou mudar a versão no arquivo src/MercadoPago/Version.php

2022-07-14 22:02 UTC, eltinMeli commented on README.md
> +`composer require "mercadopago/dx-php:2.4.8"` for PHP7 or `composer require "mercadopago/dx-php:1.12.6"` for PHP5.6.
```suggestion
`composer require "mercadopago/dx-php:2.4.9"` for PHP7 or `composer require "mercadopago/dx-php:1.12.5"` for PHP5.6.
```

2022-07-15 14:50 UTC, lucmkz commented on README.md
> +`composer require "mercadopago/dx-php:2.4.8"` for PHP7 or `composer require "mercadopago/dx-php:1.12.6"` for PHP5.6.
@eltinMeli feito!

2022-07-15 17:04 UTC, eltinMeli approved these changes

2022-07-15 17:06 UTC, merged

2022-07-15 20:20 UTC, mtferreira commented
opa pessoal, poderiam gerar a tag pra gnt atualizar?