add filed barcode and verification_code in transaction_details
mercadopago/sdk-php pull request #499
Opened 2024-02-22 18:49 UTC by edmarSoaress

## Changes made to the feature:
 * Barcode and verification code added into transaction_details

2024-02-22 19:23 UTC, rhames07 approved these changes

2024-02-23 14:10 UTC, lucmantovani approved these changes

2024-02-23 17:06 UTC, gdeandradero requested changes
não é pra por em transaction details? aqui tá em transaction data

2024-02-23 17:18 UTC, edmarSoaress commented
Perdão gente, comi bola

2024-02-23 17:26 UTC, gdeandradero approved these changes

2024-02-23 18:13 UTC, merged